# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: synthetic_model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15synthetic_model.proto\x12 hitszids.wf.syntheticdata.api.v1\"\xa2\x01\n\x10SyntheticRequest\x12\x1e\n\x16to_synthetic_file_path\x18\x01 \x01(\t\x12\x17\n\x0fmodel_save_path\x18\x02 \x01(\t\x12\x12\n\ntabel_type\x18\x03 \x01(\t\x12\x12\n\nmodel_type\x18\x04 \x01(\t\x12\x13\n\x0bprimary_key\x18\x05 \x01(\t\x12\x18\n\x10\x61nonymize_fields\x18\x06 \x01(\t\"M\n\x11SyntheticResponse\x12\x38\n\x06status\x18\x01 \x01(\x0b\x32(.hitszids.wf.syntheticdata.api.v1.Status\"Q\n\x06Status\x12:\n\x04\x63ode\x18\x01 \x01(\x0e\x32,.hitszids.wf.syntheticdata.api.v1.StatusCode\x12\x0b\n\x03msg\x18\x02 \x01(\t*\xfb\x01\n\nStatusCode\x12\x06\n\x02OK\x10\x00\x12\x14\n\x0fPARAMETER_ERROR\x10\x90N\x12\x14\n\x0f\x46ILE_READ_ERROR\x10\x91N\x12\x1c\n\x17PRIMARY_NOT_EXIST_ERROR\x10\x92N\x12\x1b\n\x16\x41nonymize_Fields_ERROR\x10\x93N\x12!\n\x1c\x41nonymize_Fields_FAKER_ERROR\x10\x94N\x12\x15\n\x10MODEL_TYPE_ERROR\x10\x95N\x12\x15\n\x10TABLE_TYPE_ERROR\x10\x96N\x12\x16\n\x11MODEL_TRAIN_ERROR\x10\x97N\x12\x15\n\x10MODEL_SAVE_ERROR\x10\x98N*8\n\tTableType\x12\x0b\n\x07TABULAR\x10\x00\x12\x0e\n\nRELATIONAL\x10\x01\x12\x0e\n\nTIMESERIES\x10\x02*\\\n\tModelType\x12\x0e\n\nTVAE_MODEL\x10\x00\x12\x0f\n\x0b\x43TGAN_MODEL\x10\x01\x12\x19\n\x15GAUSSIAN_COPULA_MODEL\x10\x02\x12\x13\n\x0f\x43OPULAGAN_MODEL\x10\x03\x32\x94\x01\n\x15SyntheticModelService\x12{\n\x0eSyntheticModel\x12\x32.hitszids.wf.syntheticdata.api.v1.SyntheticRequest\x1a\x33.hitszids.wf.syntheticdata.api.v1.SyntheticResponse\"\x00\x42<\n$org.hitszids.wf.syntheticdata.api.v1B\x12SyntheticDataProtoP\x01\x62\x06proto3')

_STATUSCODE = DESCRIPTOR.enum_types_by_name['StatusCode']
StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
_TABLETYPE = DESCRIPTOR.enum_types_by_name['TableType']
TableType = enum_type_wrapper.EnumTypeWrapper(_TABLETYPE)
_MODELTYPE = DESCRIPTOR.enum_types_by_name['ModelType']
ModelType = enum_type_wrapper.EnumTypeWrapper(_MODELTYPE)
OK = 0
PARAMETER_ERROR = 10000
FILE_READ_ERROR = 10001
PRIMARY_NOT_EXIST_ERROR = 10002
Anonymize_Fields_ERROR = 10003
Anonymize_Fields_FAKER_ERROR = 10004
MODEL_TYPE_ERROR = 10005
TABLE_TYPE_ERROR = 10006
MODEL_TRAIN_ERROR = 10007
MODEL_SAVE_ERROR = 10008
TABULAR = 0
RELATIONAL = 1
TIMESERIES = 2
TVAE_MODEL = 0
CTGAN_MODEL = 1
GAUSSIAN_COPULA_MODEL = 2
COPULAGAN_MODEL = 3


_SYNTHETICREQUEST = DESCRIPTOR.message_types_by_name['SyntheticRequest']
_SYNTHETICRESPONSE = DESCRIPTOR.message_types_by_name['SyntheticResponse']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
SyntheticRequest = _reflection.GeneratedProtocolMessageType('SyntheticRequest', (_message.Message,), {
  'DESCRIPTOR' : _SYNTHETICREQUEST,
  '__module__' : 'synthetic_model_pb2'
  # @@protoc_insertion_point(class_scope:hitszids.wf.syntheticdata.api.v1.SyntheticRequest)
  })
_sym_db.RegisterMessage(SyntheticRequest)

SyntheticResponse = _reflection.GeneratedProtocolMessageType('SyntheticResponse', (_message.Message,), {
  'DESCRIPTOR' : _SYNTHETICRESPONSE,
  '__module__' : 'synthetic_model_pb2'
  # @@protoc_insertion_point(class_scope:hitszids.wf.syntheticdata.api.v1.SyntheticResponse)
  })
_sym_db.RegisterMessage(SyntheticResponse)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'synthetic_model_pb2'
  # @@protoc_insertion_point(class_scope:hitszids.wf.syntheticdata.api.v1.Status)
  })
_sym_db.RegisterMessage(Status)

_SYNTHETICMODELSERVICE = DESCRIPTOR.services_by_name['SyntheticModelService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$org.hitszids.wf.syntheticdata.api.v1B\022SyntheticDataProtoP\001'
  _STATUSCODE._serialized_start=387
  _STATUSCODE._serialized_end=638
  _TABLETYPE._serialized_start=640
  _TABLETYPE._serialized_end=696
  _MODELTYPE._serialized_start=698
  _MODELTYPE._serialized_end=790
  _SYNTHETICREQUEST._serialized_start=60
  _SYNTHETICREQUEST._serialized_end=222
  _SYNTHETICRESPONSE._serialized_start=224
  _SYNTHETICRESPONSE._serialized_end=301
  _STATUS._serialized_start=303
  _STATUS._serialized_end=384
  _SYNTHETICMODELSERVICE._serialized_start=793
  _SYNTHETICMODELSERVICE._serialized_end=941
# @@protoc_insertion_point(module_scope)
