# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import  synthetic_model_pb2 as synthetic__model__pb2


class SyntheticModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyntheticModel = channel.unary_unary(
                '/hitszids.wf.syntheticdata.api.v1.SyntheticModelService/SyntheticModel',
                request_serializer=synthetic__model__pb2.SyntheticRequest.SerializeToString,
                response_deserializer=synthetic__model__pb2.SyntheticResponse.FromString,
                )


class SyntheticModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SyntheticModel(self, request, context):
        """仿真数据生成模型服务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyntheticModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyntheticModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SyntheticModel,
                    request_deserializer=synthetic__model__pb2.SyntheticRequest.FromString,
                    response_serializer=synthetic__model__pb2.SyntheticResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hitszids.wf.syntheticdata.api.v1.SyntheticModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SyntheticModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SyntheticModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hitszids.wf.syntheticdata.api.v1.SyntheticModelService/SyntheticModel',
            synthetic__model__pb2.SyntheticRequest.SerializeToString,
            synthetic__model__pb2.SyntheticResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
