# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: synthetic_sample.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16synthetic_sample.proto\x12\'hitszids.wf.syntheticdata.sample.api.v1\"\x88\x01\n\x10SyntheticRequest\x12\x1b\n\x13real_data_file_path\x18\x01 \x01(\t\x12\x12\n\nmodel_path\x18\x02 \x01(\t\x12\x12\n\nmodel_type\x18\x03 \x01(\t\x12\x15\n\rsample_number\x18\x04 \x01(\x05\x12\x18\n\x10\x61nonymize_fields\x18\x05 \x01(\t\"\x83\x01\n\x11SyntheticResponse\x12?\n\x06status\x18\x01 \x01(\x0b\x32/.hitszids.wf.syntheticdata.sample.api.v1.Status\x12\x16\n\x0esynthetic_data\x18\x02 \x01(\t\x12\x15\n\rprivacy_score\x18\x03 \x01(\x02\"X\n\x06Status\x12\x41\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x33.hitszids.wf.syntheticdata.sample.api.v1.StatusCode\x12\x0b\n\x03msg\x18\x02 \x01(\t*\xce\x01\n\nStatusCode\x12\x06\n\x02OK\x10\x00\x12\x15\n\x0fPARAMETER_ERROR\x10\xa0\x9c\x01\x12\x15\n\x0f\x46ILE_READ_ERROR\x10\xa1\x9c\x01\x12\x1c\n\x16\x41nonymize_Fields_ERROR\x10\xa2\x9c\x01\x12\x16\n\x10MODEL_TYPE_ERROR\x10\xa3\x9c\x01\x12\x16\n\x10MODEL_LOAD_ERROR\x10\xa4\x9c\x01\x12!\n\x1bSAMPLE_DATA_GENERATOR_ERROR\x10\xa5\x9c\x01\x12\x19\n\x13PRIVACY_SCORE_ERROR\x10\xa6\x9c\x01\x32\xa5\x01\n\x16SyntheticSampleService\x12\x8a\x01\n\x0fSyntheticSample\x12\x39.hitszids.wf.syntheticdata.sample.api.v1.SyntheticRequest\x1a:.hitszids.wf.syntheticdata.sample.api.v1.SyntheticResponse\"\x00\x42I\n+org.hitszids.wf.syntheticdata.sample.api.v1B\x18SyntheticDataSampleProtoP\x01\x62\x06proto3')

_STATUSCODE = DESCRIPTOR.enum_types_by_name['StatusCode']
StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
OK = 0
PARAMETER_ERROR = 20000
FILE_READ_ERROR = 20001
Anonymize_Fields_ERROR = 20002
MODEL_TYPE_ERROR = 20003
MODEL_LOAD_ERROR = 20004
SAMPLE_DATA_GENERATOR_ERROR = 20005
PRIVACY_SCORE_ERROR = 20006


_SYNTHETICREQUEST = DESCRIPTOR.message_types_by_name['SyntheticRequest']
_SYNTHETICRESPONSE = DESCRIPTOR.message_types_by_name['SyntheticResponse']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
SyntheticRequest = _reflection.GeneratedProtocolMessageType('SyntheticRequest', (_message.Message,), {
  'DESCRIPTOR' : _SYNTHETICREQUEST,
  '__module__' : 'synthetic_sample_pb2'
  # @@protoc_insertion_point(class_scope:hitszids.wf.syntheticdata.sample.api.v1.SyntheticRequest)
  })
_sym_db.RegisterMessage(SyntheticRequest)

SyntheticResponse = _reflection.GeneratedProtocolMessageType('SyntheticResponse', (_message.Message,), {
  'DESCRIPTOR' : _SYNTHETICRESPONSE,
  '__module__' : 'synthetic_sample_pb2'
  # @@protoc_insertion_point(class_scope:hitszids.wf.syntheticdata.sample.api.v1.SyntheticResponse)
  })
_sym_db.RegisterMessage(SyntheticResponse)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'synthetic_sample_pb2'
  # @@protoc_insertion_point(class_scope:hitszids.wf.syntheticdata.sample.api.v1.Status)
  })
_sym_db.RegisterMessage(Status)

_SYNTHETICSAMPLESERVICE = DESCRIPTOR.services_by_name['SyntheticSampleService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n+org.hitszids.wf.syntheticdata.sample.api.v1B\030SyntheticDataSampleProtoP\001'
  _STATUSCODE._serialized_start=431
  _STATUSCODE._serialized_end=637
  _SYNTHETICREQUEST._serialized_start=68
  _SYNTHETICREQUEST._serialized_end=204
  _SYNTHETICRESPONSE._serialized_start=207
  _SYNTHETICRESPONSE._serialized_end=338
  _STATUS._serialized_start=340
  _STATUS._serialized_end=428
  _SYNTHETICSAMPLESERVICE._serialized_start=640
  _SYNTHETICSAMPLESERVICE._serialized_end=805
# @@protoc_insertion_point(module_scope)
